# Generated by Django 5.1.1 on 2024-10-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KERELA_MODEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DURATION', models.CharField(max_length=100)),
                ('HOTELS', models.CharField(max_length=100)),
                ('BUDGET', models.BigIntegerField()),
                ('CITIES', models.CharField(max_length=100)),
            ],
        ),
    ]
